trans_table = {
    225: 'a',
    224: 'a',
    7843: 'a',
    227: 'a',
    7841: 'a',
    259: 'a',
    7855: 'a',
    7857: 'a',
    7859: 'a',
    7861: 'a',
    7863: 'a',
    226: 'a',
    7845: 'a',
    7847: 'a',
    7849: 'a',
    7851: 'a',
    7853: 'a',
    233: 'e',
    232: 'e',
    7867: 'e',
    7869: 'e',
    7865: 'e',
    234: 'e',
    7871: 'e',
    7873: 'e',
    7875: 'e',
    7877: 'e',
    7879: 'e',
    243: 'o',
    242: 'o',
    7887: 'o',
    245: 'o',
    7885: 'o',
    244: 'o',
    7889: 'o',
    7891: 'o',
    7893: 'o',
    7895: 'o',
    7897: 'o',
    417: 'o',
    7899: 'o',
    7901: 'o',
    7903: 'o',
    7905: 'o',
    7907: 'o',
    237: 'i',
    236: 'i',
    7881: 'i',
    297: 'i',
    7883: 'i',
    250: 'u',
    249: 'u',
    7911: 'u',
    361: 'u',
    7909: 'u',
    432: 'u',
    7913: 'u',
    7915: 'u',
    7917: 'u',
    7919: 'u',
    7921: 'u',
    253: 'y',
    7923: 'y',
    7927: 'y',
    7929: 'y',
    7925: 'y',
    273: 'd'
}

provinces = {
    'An Giang': [(-50.0, -296.0), {'arg': '    An\nGiang', 'align': 'center', 'font': ("Times New Roman", 7, 'bold')}],
    'Kon Tum': [(91.0, -84.0), {'arg': 'Kon Tum', 'align': 'center', 'font': ("Times New Roman", 8, 'bold')}],
    'Ba Ria - Vung Tau': [(44.0, -287.0), {'arg': 'Bà Rịa - Vũng Tàu', 'align': 'left', 'font': ("Times New Roman", 7, 'bold')}],
    'Lai Chau': [(-148.0, 290.0), {'arg': 'Lai Châu', 'align': 'center', 'font': ("Times New Roman", 9, 'bold')}],
    'Bac Giang': [(14.0, 242.0), {'arg': 'Bắc Giang', 'align': 'center', 'font': ("Times New Roman", 7, 'bold')}],
    'Lam Dong': [(88.0, -234.0), {'arg': 'Lâm Đồng', 'align': 'center', 'font': ("Times New Roman", 8, 'bold')}],
    'Bac Kan': [(-18.0, 291.0), {'arg': 'Bắc Kạn', 'align': 'center', 'font': ("Times New Roman", 7, 'bold')}],
    'Lang Son': [(15.0, 260.0), {'arg': 'Lạng\nSơn', 'align': 'center', 'font': ("Times New Roman", 8, 'bold')}],
    'Bac Lieu': [(-34.0, -356.0), {'arg': 'Bạc\nLiêu', 'align': 'center', 'font': ("Times New Roman", 7, 'bold')}],
    'Lao Cai': [(-100.0, 282.0), {'arg': 'Lào\nCai', 'align': 'center', 'font': ("Times New Roman", 8, 'bold')}],
    'Bac Ninh': [(80.00, 166.00), {'arg': 'Bắc Ninh', 'align': 'center', 'font': ("Times New Roman", 7, 'bold')}],
    'Long An': [(-2.00,-278.00), {'arg': 'Long An', 'align': 'center', 'font': ("Times New Roman", 7, 'bold')}],
    'Ben Tre': [(24.00,-310.00), {'arg': 'Bến Tre', 'align': 'center', 'font': ("Times New Roman", 7, 'bold')}],
    'Nam Dinh': [(20.00,187.00), {'arg': 'Nam Định', 'align': 'center', 'font': ("Times New Roman", 7, 'bold')}],
    'Binh Dinh': [(136.00,-118.00), {'arg': 'Bình\nĐịnh', 'align': 'center', 'font': ("Times New Roman", 7, 'bold')}],
    'Nghe An': [(-61.00,139.00), {'arg': 'Nghệ An', 'align': 'center', 'font': ("Times New Roman", 9, 'bold')}],
    'Binh Duong': [(26.00,-260.00), {'arg': 'Bình\nDương', 'align': 'center', 'font': ("Times New Roman", 6, 'bold')}],
    'Ninh Binh': [(-15.00,180.00), {'arg': 'Ninh\n   Bình', 'align': 'center', 'font': ("Times New Roman", 6, 'bold')}],
    'Binh Phuoc': [(36.00,-237.00), {'arg': ' Bình\nPhước', 'align': 'center', 'font': ("Times New Roman", 8, 'bold')}],
    'Ninh Thuan': [(134.00,-239.00), {'arg': ' Ninh\nThuận', 'align': 'center', 'font': ("Times New Roman", 7, 'bold')}],
    'Binh Thuan': [(88.00,-260.00), {'arg': 'Bình Thuận', 'align': 'center', 'font': ("Times New Roman", 7, 'bold')}],
    'Phu Tho': [(-52.00,234.00), {'arg': 'Phú\nThọ', 'align': 'center', 'font': ("Times New Roman", 7, 'bold')}],
    'Ca Mau': [(-54.00,-365.00), {'arg': 'Cà\nMau', 'align': 'center', 'font': ("Times New Roman", 7, 'bold')}],
    'Phu Yen': [(141.00,-166.00), {'arg': 'Phú\nYên', 'align': 'center', 'font': ("Times New Roman", 7, 'bold')}],
    'Can Tho': [(-35.00,-315.00), {'arg': 'Cần\n Thơ', 'align': 'center', 'font': ("Times New Roman", 6, 'bold')}],
    'Quang Binh': [(5.00,49.00), {'arg': 'Quảng\n  Bình', 'align': 'center', 'font': ("Times New Roman", 7, 'bold')}],
    'Cao Bang': [(0.00,309.00), {'arg': 'Cao Bằng', 'align': 'center', 'font': ("Times New Roman", 7, 'bold')}],
    'Quang Nam': [(89.00,-50.00), {'arg': 'Quảng\n  Nam', 'align': 'center', 'font': ("Times New Roman", 9, 'bold')}],
    'Da Nang': [(106.00,-17.00), {'arg': 'Đà Nẵng', 'align': 'center', 'font': ("Times New Roman", 7, 'bold')}],
    'Quang Ngai': [(120.00,-76.00), {'arg': 'Quảng\n  Ngãi', 'align': 'center', 'font': ("Times New Roman", 7, 'bold')}],
    'Dak Lak': [(102.00,-186.00), {'arg': 'Đắk\nLắk', 'align': 'center', 'font': ("Times New Roman", 9, 'bold')}],
    'Quang Ninh': [(53.00,232.00), {'arg': '   Quảng\nNinh', 'align': 'center', 'font': ("Times New Roman", 7, 'bold')}],
    'Dak Nong': [(76.00,-216.00), {'arg': ' Đắk\nNông', 'align': 'center', 'font': ("Times New Roman", 8, 'bold')}],
    'Quang Tri': [(38.00,9.00), {'arg': 'Quảng\n   Trị', 'align': 'center', 'font': ("Times New Roman", 7, 'bold')}],
    'Dien Bien': [(-145.00,255.00), {'arg': 'Điện\nBiên', 'align': 'center', 'font': ("Times New Roman", 8, 'bold')}],
    'Soc Trang': [(-10.00,-342.00), {'arg': '  Sóc\nTrăng', 'align': 'center', 'font': ("Times New Roman", 7, 'bold')}],
    'Dong Nai': [(50.00,-269.00), {'arg': 'Đồng\n Nai', 'align': 'center', 'font': ("Times New Roman", 7, 'bold')}],
    'Son La': [(-101.00,233.00), {'arg': 'Sơn La', 'align': 'center', 'font': ("Times New Roman", 9, 'bold')}],
    'Dong Thap': [(-28.00,-293.00), {'arg': 'Đồng\n   Tháp', 'align': 'center', 'font': ("Times New Roman", 7, 'bold')}],
    'Tay Ninh': [(-2.00,-252.00), {'arg': ' Tây\nNinh', 'align': 'center', 'font': ("Times New Roman", 7, 'bold')}],
    'Gia Lai': [(95.00,-128.00), {'arg': 'Gia Lai', 'align': 'center', 'font': ("Times New Roman", 9, 'bold')}],
    'Thai Binh': [(20.00,201.00), {'arg': 'Thái Bình', 'align': 'center', 'font': ("Times New Roman", 7, 'bold')}],
    'Ha Giang': [(-68.00,305.00), {'arg': '      Hà\nGiang', 'align': 'center', 'font': ("Times New Roman", 8, 'bold')}],
    'Thai Nguyen': [(-17.00,254.00), {'arg': '  Thái\nNguyên', 'align': 'center', 'font': ("Times New Roman", 7, 'bold')}],
    'Ha Nam': [(78.00,102.00), {'arg': 'Hà Nam', 'align': 'center', 'font': ("Times New Roman", 7, 'bold')}],
    'Thanh Hoa': [(-37.00,164.00), {'arg': 'Thanh\n   Hóa', 'align': 'center', 'font': ("Times New Roman", 8, 'bold')}],
    'Ha Noi': [(-21.00,215.00), {'arg': 'Hà\nNội', 'align': 'center', 'font': ("Times New Roman", 7, 'bold')}],
    'Thua Thien Hue': [(70.00,-11.00), {'arg': 'Thừa Thiên\n       Huế', 'align': 'center', 'font': ("Times New Roman", 7, 'bold')}],
    'Ha Tinh': [(-25.00,94.00), {'arg': 'Hà Tĩnh', 'align': 'center', 'font': ("Times New Roman", 7, 'bold')}],
    'Tien Giang': [(10.00,-296.00), {'arg': 'Tiền Giang', 'align': 'center', 'font': ("Times New Roman", 7, 'bold')}],
    'Hai Duong': [(82.00,145.00), {'arg': 'Hải Dương', 'align': 'center', 'font': ("Times New Roman", 7, 'bold')}],
    'Ho Chi Minh': [(25.00,-286.00), {'arg': 'Hồ\nChí\n  Minh', 'align': 'center', 'font': ("Times New Roman", 6, 'bold')}],
    'Hai Phong': [(37.00,213.00), {'arg': 'Hải Phòng', 'align': 'center', 'font': ("Times New Roman", 7, 'bold')}],
    'Tra Vinh': [(8.00,-334.00), {'arg': 'Trà\n   Vinh', 'align': 'center', 'font': ("Times New Roman", 7, 'bold')}],
    'Hau Giang': [(-29.00,-331.00), {'arg': '     Hậu\nGiang', 'align': 'center', 'font': ("Times New Roman", 6, 'bold')}],
    'Tuyen Quang': [(-47.00,271.00), {'arg': 'Tuyên\n Quang', 'align': 'center', 'font': ("Times New Roman", 7, 'bold')}],
    'Hoa Binh': [(-37.00,203.00), {'arg': 'Hòa\n Bình', 'align': 'center', 'font': ("Times New Roman", 8, 'bold')}],
    'Vinh Long': [(-10.00,-314.00), {'arg': 'Vĩnh\nLong', 'align': 'center', 'font': ("Times New Roman", 6, 'bold')}],
    'Hung Yen': [(80.00,123.00), {'arg': 'Hưng Yên', 'align': 'center', 'font': ("Times New Roman", 7, 'bold')}],
    'Vinh Phuc': [(80.00,187.00), {'arg': 'Vĩnh Phúc', 'align': 'center', 'font': ("Times New Roman", 7, 'bold')}],
    'Khanh Hoa': [(137.00,-211.00), {'arg': 'Khánh\n   Hòa', 'align': 'center', 'font': ("Times New Roman", 7, 'bold')}],
    'Yen Bai': [(-81.00,263.00), {'arg': 'Yên Bái', 'align': 'center', 'font': ("Times New Roman", 8, 'bold')}],
    'Kien Giang': [(-53.00,-323.00), {'arg': '  Kiên\nGiang', 'align': 'center', 'font': ("Times New Roman", 7, 'bold')}]
}

alt_provinces = {
    'Ba Ria Vung Tau': 'Ba Ria - Vung Tau',
    'Vung Tau': 'Ba Ria - Vung Tau',
    'Hue': 'Thua Thien Hue',
    'Thua Thien - Hue': 'Thua Thien Hue',
    'Tp Ho Chi Minh': 'Ho Chi Minh',
    'Sai Gon': 'Ho Chi Minh'
}
